extends:
  - "@commitlint/config-conventional"
rules:
  type-enum:
    - 2
    - always
    - [feat, fix, perf, refactor, docs, test, build, ci, chore, revert, security]
  scope-enum:
    - 2
    - always
    - [core, enterprise, cli, operator, helm, ui, observability, security, docs, deps, release, infra, tests, repo]
  scope-empty:
    - 2
    - never
  subject-case:
    - 2
    - always
    - [lower-case, sentence-case]
  subject-full-stop:
    - 2
    - never
    - "."
  header-max-length:
    - 2
    - always
    - 72
